### PR TITLE
GH-265 Expose entity-editors ManagerServices for custom components

### PR DESCRIPTION
**Pull request by anotherhale**
### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all changes are documented in CHANGESLOG.md and README.md

### CODE REVIEW

**Comment by eitanfr** [comment]
Hi,
Thx for the PR, can you please provide some context for the PR and way is in needed?

**Comment by anotherhale** [comment]
See my comment here.
https://github.com/articodeltd/angular-cesium/issues/265#issuecomment-566815737
If you need more details I can provide them.

**Comment by anotherhale** [comment]
The `PolylinesEdtitor`'s `init` method requires a `PolylinesManagerService`:
https://github.com/articodeltd/angular-cesium/blob/e3a897d2000907b53b6e20b4264d8da833ff7dcf/projects/demo/src/app/components/custom-range-and-bearing/custom-range-and-bearing.component.ts#L141-L147
But the PolylinesManagerService is not publicly exported and so it cannot be imported into the custom component.

**Comment by mmoriani** [comment]
It would be interesting for me too 💃

**Comment by eitanfr** [comment]
Hi,
1. You shouldn't call `init()` function by yourself the ` <range-and-bearing/>` does it internally.
2. The `PolylinesManagerService` polyline is provided by the `<polygons-editor/>` which is used by the  ` <range-and-bearing/>` therefore you dont need to provide by yourself.
3. I understand there was an issue of creating multiple range-and-bearings lines, this already works out of the box, just use do:
```
const rnb = this.rangeAndBearing.create(); // will create new instance of RNB every time you do create()
```

I believe the confusion was because of the old docs, please have a look at the [editors doc](https://docs.angular-cesium.com/widgets/shape-editors) also check the [range and bearing doc](https://docs.angular-cesium.com/widgets/range-and-bearing).
Let me know if it is clear and if you have any more questions.

**Comment by mmoriani** [comment]
Hi, i read your reply and probably i misunderstood anotherhale's PR, but exporting the "Geometry ManagerServices" would be useful to get a newly drawn polygon to flyTo() it.

In particular i have to:

1. Draw polygons
2. Save them to db
3. Close map.
4. Load and draw polygons on the map
5. flyTo() Them

I read the docs and navigate through code, but i haven't found a solution.

I thought that using the "PolygonManagerService" I can take the polygon by id and flyTo() it.

thanks in advance!

**Comment by eitanfr** [comment]
> Hi, i read your reply and probably i misunderstood anotherhale's PR, but exporting the "Geometry ManagerServices" would be useful to get a newly drawn polygon to flyTo() it.
> 
> In particular i have to:
> 
> 1. Draw polygons
> 2. Save them to db
> 3. Close map.
> 4. Load and draw polygons on the map
> 5. flyTo() Them
> 
> I read the docs and navigate through code, but i haven't found a solution.
> 
> I thought that using the "PolygonManagerService" I can take the polygon by id and flyTo() it.
> 
> thanks in advance!

so about your question a couple of things:
1. if you want to do `flyTo` to a drawn polygon from the shape editors you always can do:
```
  this.editing$ = this.polygonEditor.create();
const cartesian3Positions = this.editing$.getCurrentPoints();
const center = Cesium.BoundingSphere.fromPoints(cartesian3Positions).center;
cesiumCamera.flyTo({destination: center})
```
2. I dont recommand managing your polygons with the Gemometry Drawer Tools, the tool should be used for creating and edit polygons, for display use the `ac-layer` component.
The recommended data flow should be:
_Create polygon using the Drawer Tool -> save to the local store/db -> display the polygons in a polygons component using `ac-layer`._

**Comment by anotherhale** [comment]
I still think that this is a reasonable request to open the API to the ManagerServices so that others can create their own custom components.

**Comment by eitanfr** [comment]
@anotherhale the ManagerServices is an internal container for all the editable instances and used as a way to share data between the editor component and its service. For example, the `PolylinesEditorService` creates new instances of an editable polyline that are managed in the EditablePolylineManagerService internally, the editor-component is the provider of the ManagerService. Therefore the ManagerServices are private. 

Not sure what you meant in _so that others can create their own custom components_ :
* each editor instance is returned by the `create()` or `edit()` methods 
* for creating another type of editors like an "ellipsoid" it will be a PR :)

**Comment by mmoriani** [comment]
> > Hi, i read your reply and probably i misunderstood anotherhale's PR, but exporting the "Geometry ManagerServices" would be useful to get a newly drawn polygon to flyTo() it.
> > In particular i have to:
> > 
> > 1. Draw polygons
> > 2. Save them to db
> > 3. Close map.
> > 4. Load and draw polygons on the map
> > 5. flyTo() Them
> > 
> > I read the docs and navigate through code, but i haven't found a solution.
> > I thought that using the "PolygonManagerService" I can take the polygon by id and flyTo() it.
> > thanks in advance!
> 
> so about your question a couple of things:
> 
> 1. if you want to do `flyTo` to a drawn polygon from the shape editors you always can do:
> 
> ```
>   this.editing$ = this.polygonEditor.create();
> const cartesian3Positions = this.editing$.getCurrentPoints();
> const center = Cesium.BoundingSphere.fromPoints(cartesian3Positions).center;
> cesiumCamera.flyTo({destination: center})
> ```
> 
> 1. I dont recommand managing your polygons with the Gemometry Drawer Tools, the tool should be used for creating and edit polygons, for display use the `ac-layer` component.
>    The recommended data flow should be:
>    _Create polygon using the Drawer Tool -> save to the local store/db -> display the polygons in a polygons component using `ac-layer`._

I am really grateful  for your help!
I did it a bit differently:

`const cartesian3Positions = this.editingArea$.getCurrentPoints().map(e => e.getPosition());
 const s = Cesium.BoundingSphere.fromPoints(cartesian3Positions);
 this.cameraService.getCamera().flyToBoundingSphere(s);`

Btw i need to use _Gemometry Drawer Tools_ cause polygons should be editable (or deletable) after loading them from db and it could be useful having a better way to distinguish them in MapEvents, maybe a custom property?

**Comment by eitanfr** [comment]
> > > Hi, i read your reply and probably i misunderstood anotherhale's PR, but exporting the "Geometry ManagerServices" would be useful to get a newly drawn polygon to flyTo() it.
> > > In particular i have to:
> > > 
> > > 1. Draw polygons
> > > 2. Save them to db
> > > 3. Close map.
> > > 4. Load and draw polygons on the map
> > > 5. flyTo() Them
> > > 
> > > I read the docs and navigate through code, but i haven't found a solution.
> > > I thought that using the "PolygonManagerService" I can take the polygon by id and flyTo() it.
> > > thanks in advance!
> > 
> > 
> > so about your question a couple of things:
> > 
> > 1. if you want to do `flyTo` to a drawn polygon from the shape editors you always can do:
> > 
> > ```
> >   this.editing$ = this.polygonEditor.create();
> > const cartesian3Positions = this.editing$.getCurrentPoints();
> > const center = Cesium.BoundingSphere.fromPoints(cartesian3Positions).center;
> > cesiumCamera.flyTo({destination: center})
> > ```
> > 
> > 
> > 
> > 1. I dont recommand managing your polygons with the Gemometry Drawer Tools, the tool should be used for creating and edit polygons, for display use the `ac-layer` component.
> >    The recommended data flow should be:
> >    _Create polygon using the Drawer Tool -> save to the local store/db -> display the polygons in a polygons component using `ac-layer`._
> 
> I am really grateful for your help!
> I did it a bit differently:
> 
> ```
> const cartesian3Positions = this.editingArea$.getCurrentPoints().map(e => e.getPosition());
>  const s = Cesium.BoundingSphere.fromPoints(cartesian3Positions);
>  this.cameraService.getCamera().flyToBoundingSphere(s);
> ```
> 
> Btw i need to use _Gemometry Drawer Tools_ cause polygons should be editable (or deletable) after loading them from db and it could be useful having a better way to distinguish them in MapEvents, maybe a custom property?

Cool,
Yes, you can distinguish the edit polygons by their `id` all edit polygons acEntities have a `id` that starts with `edit-polygon-[id]`.

**Comment by anotherhale** [comment]
I now understand the proper way to create R&B. Thanks for updating docs.

**Pull request closed without merging**
